### PR TITLE
some Isomap procedural tweaks

### PR DESCRIPTION
**Pull request by topepo**
* Added a `verbose` option and set to `TRUE`. This will be good once these get wrapped inside of  resampling routines
* Added a cap on the number of neighbors. Otherwise, there is an error: 
```r
Error in RANN::nn2(data = x, query = x, k = k + 1, treetype = treetype,  : 
  Cannot find more nearest neighbours than there are points
```

Fo the apply function, where you `rbind` the out of sample data with the training set, I used 
```r
lknng <- makeKNNgraph(rbind(indata, orgdata),
                      k = min(norg, pars$knn), eps = pars$eps)
```
but that may not be the best idea (I have no idea).

### CODE REVIEW

**Comment by gdkrmr** [comment]
you can suppress the output of every method by setting `.mute = c("message", "output")` in `embed`.
Including `"message"`, suppresses normal print output, `"output"` suppresses error messages, warnings and messages, it is not entirely clear to me, you can check out `?sink` for more information.
I should make this more clear in the documentation of embed.

```R
emb <- embed(loadDataSet("Iris"), "Isomap", .mute = c("message"))
```

**Comment by topepo** [comment]
In the Rd files is is minus the dot:
```r
emb2 <- embed(dat[samp], "Isomap", mute = NULL, knn = 10)
```
Should I delete the PR?

**Comment by gdkrmr** [comment]
keep the part that fixes the bug with the nearest neighbors and add the fix for the documentation.
Thanks by the way for checking all my code!

**Comment by topepo** [comment]
No problem; thanks for the package

**Comment by gdkrmr** [comment]
i am closing it, 
- The `RANN` package does the checking for the number of neighbors and gives a useful error message, therefore no extra code for error checking needed.
- I am a friend of failing programs and not helping the user silently: If people put more neighbors than point in their code then probably there is something wrong and the user should be made aware of it, in Isomap one should use `k << n`, else one could do a simple MDS or PCA anyways.

**Pull request closed without merging**
